[2024-05-28T22:17:04.544+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T22:17:04.565+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:16:47.856181+00:00 [queued]>
[2024-05-28T22:17:04.573+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:16:47.856181+00:00 [queued]>
[2024-05-28T22:17:04.574+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-28T22:17:04.585+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-05-28 22:16:47.856181+00:00
[2024-05-28T22:17:04.594+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=297) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T22:17:04.595+0000] {standard_task_runner.py:63} INFO - Started process 299 to run task
[2024-05-28T22:17:04.595+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'data_delivery', 'manual__2024-05-28T22:16:47.856181+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/sales_data_pipeline.py', '--cfg-path', '/tmp/tmps_l1rhv3']
[2024-05-28T22:17:04.597+0000] {standard_task_runner.py:91} INFO - Job 84: Subtask data_delivery
[2024-05-28T22:17:04.607+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T22:17:04.636+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:16:47.856181+00:00 [running]> on host 90e12a9d37bb
[2024-05-28T22:17:04.725+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud Mamdoh' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T22:16:47.856181+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T22:16:47.856181+00:00'
[2024-05-28T22:17:04.726+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T22:17:04.738+0000] {sales_data_pipeline.py:54} INFO - data_delivery started
[2024-05-28T22:17:04.739+0000] {sales_data_pipeline.py:61} ERROR - Error in data_delivery
Traceback (most recent call last):
  File "/opt/airflow/dags/sales_data_pipeline.py", line 55, in data_delivery
    load_customer_dim(**db_credentials)
TypeError: load_customer_dim() got an unexpected keyword argument 'host'
[2024-05-28T22:17:04.740+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T22:17:04.740+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T22:17:04.748+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=data_delivery, run_id=manual__2024-05-28T22:16:47.856181+00:00, execution_date=20240528T221647, start_date=20240528T221704, end_date=20240528T221704
[2024-05-28T22:17:04.768+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T22:17:04.783+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T22:17:04.785+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
