[2024-05-28T22:25:13.980+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T22:25:14.001+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:16:47.856181+00:00 [queued]>
[2024-05-28T22:25:14.007+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:16:47.856181+00:00 [queued]>
[2024-05-28T22:25:14.008+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 5
[2024-05-28T22:25:14.019+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-05-28 22:16:47.856181+00:00
[2024-05-28T22:25:14.027+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=309) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T22:25:14.028+0000] {standard_task_runner.py:63} INFO - Started process 311 to run task
[2024-05-28T22:25:14.029+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'data_delivery', 'manual__2024-05-28T22:16:47.856181+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/sales_data_pipeline.py', '--cfg-path', '/tmp/tmpc18_qdyu']
[2024-05-28T22:25:14.031+0000] {standard_task_runner.py:91} INFO - Job 88: Subtask data_delivery
[2024-05-28T22:25:14.041+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T22:25:14.069+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:16:47.856181+00:00 [running]> on host 90e12a9d37bb
[2024-05-28T22:25:14.147+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud Mamdoh' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T22:16:47.856181+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T22:16:47.856181+00:00'
[2024-05-28T22:25:14.148+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T22:25:14.159+0000] {sales_data_pipeline.py:54} INFO - data_delivery started
[2024-05-28T22:25:14.159+0000] {sales_data_pipeline.py:61} ERROR - Error in data_delivery
Traceback (most recent call last):
  File "/opt/airflow/dags/sales_data_pipeline.py", line 55, in data_delivery
    load_customer_dim()
TypeError: load_customer_dim() missing 4 required positional arguments: 'host', 'db_name', 'user', and 'password'
[2024-05-28T22:25:14.160+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T22:25:14.161+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T22:25:14.169+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=data_delivery, run_id=manual__2024-05-28T22:16:47.856181+00:00, execution_date=20240528T221647, start_date=20240528T222514, end_date=20240528T222514
[2024-05-28T22:25:14.202+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T22:25:14.214+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
