[2024-05-28T22:22:18.379+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T22:22:18.401+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:16:47.856181+00:00 [queued]>
[2024-05-28T22:22:18.408+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:16:47.856181+00:00 [queued]>
[2024-05-28T22:22:18.408+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2024-05-28T22:22:18.421+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-05-28 22:16:47.856181+00:00
[2024-05-28T22:22:18.430+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=306) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T22:22:18.431+0000] {standard_task_runner.py:63} INFO - Started process 308 to run task
[2024-05-28T22:22:18.431+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'data_delivery', 'manual__2024-05-28T22:16:47.856181+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/sales_data_pipeline.py', '--cfg-path', '/tmp/tmpkzg2w7av']
[2024-05-28T22:22:18.433+0000] {standard_task_runner.py:91} INFO - Job 87: Subtask data_delivery
[2024-05-28T22:22:18.444+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T22:22:18.471+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:16:47.856181+00:00 [running]> on host 90e12a9d37bb
[2024-05-28T22:22:18.551+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud Mamdoh' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T22:16:47.856181+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T22:16:47.856181+00:00'
[2024-05-28T22:22:18.552+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T22:22:18.564+0000] {sales_data_pipeline.py:54} INFO - data_delivery started
[2024-05-28T22:22:18.565+0000] {Load_data.py:10} INFO - Loading customer_df dimension...
[2024-05-28T22:22:18.573+0000] {Load_data.py:19} ERROR - Error loading users dimension: load_data_to_postgres() missing 4 required positional arguments: 'host', 'db_name', 'user', and 'password'
[2024-05-28T22:22:18.573+0000] {Load_data.py:23} INFO - Loading customer dimension...
[2024-05-28T22:22:18.579+0000] {Load_data.py:32} ERROR - Error loading users dimension: load_data_to_postgres() missing 4 required positional arguments: 'host', 'db_name', 'user', and 'password'
[2024-05-28T22:22:18.579+0000] {Load_data.py:36} INFO - Loading customer dimension...
[2024-05-28T22:22:18.594+0000] {Load_data.py:45} ERROR - Error loading users dimension: load_data_to_postgres() missing 4 required positional arguments: 'host', 'db_name', 'user', and 'password'
[2024-05-28T22:22:18.595+0000] {Load_data.py:49} INFO - Loading fact sales ...
[2024-05-28T22:22:18.678+0000] {Load_data.py:55} ERROR - Error loading sales fact: load_data_to_postgres() missing 4 required positional arguments: 'host', 'db_name', 'user', and 'password'
[2024-05-28T22:22:18.681+0000] {sales_data_pipeline.py:59} INFO - data_delivery done
[2024-05-28T22:22:18.681+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T22:22:18.682+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T22:22:18.689+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=data_delivery, run_id=manual__2024-05-28T22:16:47.856181+00:00, execution_date=20240528T221647, start_date=20240528T222218, end_date=20240528T222218
[2024-05-28T22:22:18.724+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T22:22:18.743+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T22:22:18.745+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
