[2024-05-28T11:17:44.952+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T11:17:44.974+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery scheduled__2024-05-27T00:00:00+00:00 [queued]>
[2024-05-28T11:17:45.131+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery scheduled__2024-05-27T00:00:00+00:00 [queued]>
[2024-05-28T11:17:45.132+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-28T11:17:45.144+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-05-27 00:00:00+00:00
[2024-05-28T11:17:45.152+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=68) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T11:17:45.153+0000] {standard_task_runner.py:63} INFO - Started process 70 to run task
[2024-05-28T11:17:45.153+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'data_delivery', 'scheduled__2024-05-27T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/sales_data_pipeline.py', '--cfg-path', '/tmp/tmpl5j8oram']
[2024-05-28T11:17:45.155+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask data_delivery
[2024-05-28T11:17:45.193+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.data_delivery scheduled__2024-05-27T00:00:00+00:00 [running]> on host b594ee19424a
[2024-05-28T11:17:45.262+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud Mamdoh' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-05-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-27T00:00:00+00:00'
[2024-05-28T11:17:45.263+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T11:17:45.276+0000] {sales_data_pipeline.py:54} INFO - data_delivery started
[2024-05-28T11:17:45.276+0000] {sales_data_pipeline.py:61} ERROR - Error in data_delivery
Traceback (most recent call last):
  File "/opt/airflow/dags/sales_data_pipeline.py", line 55, in data_delivery
    load_customer_dim(**db_credentials)
TypeError: load_customer_dim() got an unexpected keyword argument 'host'
[2024-05-28T11:17:45.277+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T11:17:45.277+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T11:17:45.285+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=data_delivery, run_id=scheduled__2024-05-27T00:00:00+00:00, execution_date=20240527T000000, start_date=20240528T111744, end_date=20240528T111745
[2024-05-28T11:17:45.326+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T11:17:45.340+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T11:17:45.342+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-28T11:24:31.600+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T11:24:31.622+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery scheduled__2024-05-27T00:00:00+00:00 [queued]>
[2024-05-28T11:24:31.631+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery scheduled__2024-05-27T00:00:00+00:00 [queued]>
[2024-05-28T11:24:31.631+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-28T11:24:31.809+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-05-27 00:00:00+00:00
[2024-05-28T11:24:31.818+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=68) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T11:24:31.819+0000] {standard_task_runner.py:63} INFO - Started process 70 to run task
[2024-05-28T11:24:31.819+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'data_delivery', 'scheduled__2024-05-27T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/sales_data_pipeline.py', '--cfg-path', '/tmp/tmpp2blmzw2']
[2024-05-28T11:24:31.821+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask data_delivery
[2024-05-28T11:24:31.863+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.data_delivery scheduled__2024-05-27T00:00:00+00:00 [running]> on host 57dc34eafbbe
[2024-05-28T11:24:31.939+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud Mamdoh' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-05-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-27T00:00:00+00:00'
[2024-05-28T11:24:31.940+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T11:24:31.953+0000] {sales_data_pipeline.py:54} INFO - data_delivery started
[2024-05-28T11:24:31.954+0000] {sales_data_pipeline.py:61} ERROR - Error in data_delivery
Traceback (most recent call last):
  File "/opt/airflow/dags/sales_data_pipeline.py", line 55, in data_delivery
    load_customer_dim(**db_credentials)
TypeError: load_customer_dim() got an unexpected keyword argument 'host'
[2024-05-28T11:24:31.954+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T11:24:31.955+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T11:24:31.964+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=data_delivery, run_id=scheduled__2024-05-27T00:00:00+00:00, execution_date=20240527T000000, start_date=20240528T112431, end_date=20240528T112431
[2024-05-28T11:24:31.992+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T11:24:32.007+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T11:24:32.009+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-28T17:02:11.545+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T17:02:11.567+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery scheduled__2024-05-27T00:00:00+00:00 [queued]>
[2024-05-28T17:02:11.574+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery scheduled__2024-05-27T00:00:00+00:00 [queued]>
[2024-05-28T17:02:11.575+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-28T17:02:11.586+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-05-27 00:00:00+00:00
[2024-05-28T17:02:11.594+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=57) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T17:02:11.595+0000] {standard_task_runner.py:63} INFO - Started process 59 to run task
[2024-05-28T17:02:11.596+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'data_delivery', 'scheduled__2024-05-27T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/sales_data_pipeline.py', '--cfg-path', '/tmp/tmpdqi_qruy']
[2024-05-28T17:02:11.598+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask data_delivery
[2024-05-28T17:02:11.610+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T17:02:11.641+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.data_delivery scheduled__2024-05-27T00:00:00+00:00 [running]> on host 0fa044a0c643
[2024-05-28T17:02:11.715+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud Mamdoh' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-05-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-27T00:00:00+00:00'
[2024-05-28T17:02:11.716+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T17:02:11.729+0000] {sales_data_pipeline.py:54} INFO - data_delivery started
[2024-05-28T17:02:11.730+0000] {sales_data_pipeline.py:61} ERROR - Error in data_delivery
Traceback (most recent call last):
  File "/opt/airflow/dags/sales_data_pipeline.py", line 55, in data_delivery
    load_customer_dim(**db_credentials)
TypeError: load_customer_dim() got an unexpected keyword argument 'host'
[2024-05-28T17:02:11.731+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T17:02:11.731+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T17:02:11.740+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=data_delivery, run_id=scheduled__2024-05-27T00:00:00+00:00, execution_date=20240527T000000, start_date=20240528T170211, end_date=20240528T170211
[2024-05-28T17:02:11.769+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T17:02:11.785+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T17:02:11.786+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-28T19:08:10.562+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T19:08:10.586+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery scheduled__2024-05-27T00:00:00+00:00 [queued]>
[2024-05-28T19:08:10.596+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery scheduled__2024-05-27T00:00:00+00:00 [queued]>
[2024-05-28T19:08:10.596+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-28T19:08:10.609+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-05-27 00:00:00+00:00
[2024-05-28T19:08:10.617+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=57) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T19:08:10.618+0000] {standard_task_runner.py:63} INFO - Started process 59 to run task
[2024-05-28T19:08:10.618+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'data_delivery', 'scheduled__2024-05-27T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/sales_data_pipeline.py', '--cfg-path', '/tmp/tmpfy_lh87h']
[2024-05-28T19:08:10.620+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask data_delivery
[2024-05-28T19:08:10.631+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T19:08:10.662+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.data_delivery scheduled__2024-05-27T00:00:00+00:00 [running]> on host 620f12c2bede
[2024-05-28T19:08:10.735+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud Mamdoh' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-05-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-27T00:00:00+00:00'
[2024-05-28T19:08:10.737+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T19:08:10.751+0000] {sales_data_pipeline.py:54} INFO - data_delivery started
[2024-05-28T19:08:10.752+0000] {sales_data_pipeline.py:61} ERROR - Error in data_delivery
Traceback (most recent call last):
  File "/opt/airflow/dags/sales_data_pipeline.py", line 55, in data_delivery
    load_customer_dim(**db_credentials)
TypeError: load_customer_dim() got an unexpected keyword argument 'host'
[2024-05-28T19:08:10.753+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T19:08:10.753+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T19:08:10.762+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=data_delivery, run_id=scheduled__2024-05-27T00:00:00+00:00, execution_date=20240527T000000, start_date=20240528T190810, end_date=20240528T190810
[2024-05-28T19:08:10.791+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T19:08:10.806+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T19:08:10.807+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-28T19:12:41.920+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T19:12:41.941+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery scheduled__2024-05-27T00:00:00+00:00 [queued]>
[2024-05-28T19:12:41.949+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery scheduled__2024-05-27T00:00:00+00:00 [queued]>
[2024-05-28T19:12:41.949+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-28T19:12:41.961+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-05-27 00:00:00+00:00
[2024-05-28T19:12:41.969+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=63) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T19:12:41.970+0000] {standard_task_runner.py:63} INFO - Started process 67 to run task
[2024-05-28T19:12:41.970+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'data_delivery', 'scheduled__2024-05-27T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/sales_data_pipeline.py', '--cfg-path', '/tmp/tmpfymhnppb']
[2024-05-28T19:12:41.973+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask data_delivery
[2024-05-28T19:12:41.985+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T19:12:42.015+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.data_delivery scheduled__2024-05-27T00:00:00+00:00 [running]> on host 90e12a9d37bb
[2024-05-28T19:12:42.103+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud Mamdoh' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-05-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-27T00:00:00+00:00'
[2024-05-28T19:12:42.104+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T19:12:42.121+0000] {sales_data_pipeline.py:54} INFO - data_delivery started
[2024-05-28T19:12:42.122+0000] {sales_data_pipeline.py:61} ERROR - Error in data_delivery
Traceback (most recent call last):
  File "/opt/airflow/dags/sales_data_pipeline.py", line 55, in data_delivery
    load_customer_dim(**db_credentials)
TypeError: load_customer_dim() got an unexpected keyword argument 'host'
[2024-05-28T19:12:42.123+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T19:12:42.124+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T19:12:42.133+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=data_delivery, run_id=scheduled__2024-05-27T00:00:00+00:00, execution_date=20240527T000000, start_date=20240528T191241, end_date=20240528T191242
[2024-05-28T19:12:42.184+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T19:12:42.200+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T19:12:42.202+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
