[2024-05-28T22:16:15.905+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T22:16:15.925+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:15:19.089785+00:00 [queued]>
[2024-05-28T22:16:15.932+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:15:19.089785+00:00 [queued]>
[2024-05-28T22:16:15.932+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-28T22:16:15.985+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-05-28 22:15:19.089785+00:00
[2024-05-28T22:16:15.994+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=288) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T22:16:15.995+0000] {standard_task_runner.py:63} INFO - Started process 290 to run task
[2024-05-28T22:16:15.995+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'data_delivery', 'manual__2024-05-28T22:15:19.089785+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/sales_data_pipeline.py', '--cfg-path', '/tmp/tmp73a7g4m6']
[2024-05-28T22:16:15.998+0000] {standard_task_runner.py:91} INFO - Job 81: Subtask data_delivery
[2024-05-28T22:16:16.054+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T22:16:16.084+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:15:19.089785+00:00 [running]> on host 90e12a9d37bb
[2024-05-28T22:16:16.327+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud Mamdoh' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T22:15:19.089785+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T22:15:19.089785+00:00'
[2024-05-28T22:16:16.328+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T22:16:16.349+0000] {sales_data_pipeline.py:66} ERROR - Error in data_delivery
Traceback (most recent call last):
  File "/opt/airflow/dags/sales_data_pipeline.py", line 58, in data_delivery
    db_credentials = load_credentials()
                     ^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/sales_data_pipeline.py", line 27, in load_credentials
    host = Variable.get("host")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable host does not exist'
[2024-05-28T22:16:16.350+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T22:16:16.351+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T22:16:16.361+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=data_delivery, run_id=manual__2024-05-28T22:15:19.089785+00:00, execution_date=20240528T221519, start_date=20240528T221615, end_date=20240528T221616
[2024-05-28T22:16:16.489+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T22:16:16.505+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T22:16:16.539+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
