[2024-05-28T22:14:25.692+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T22:14:25.713+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:08:30.636785+00:00 [queued]>
[2024-05-28T22:14:25.719+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:08:30.636785+00:00 [queued]>
[2024-05-28T22:14:25.720+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-05-28T22:14:25.731+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-05-28 22:08:30.636785+00:00
[2024-05-28T22:14:25.740+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=270) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T22:14:25.741+0000] {standard_task_runner.py:63} INFO - Started process 272 to run task
[2024-05-28T22:14:25.741+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'data_delivery', 'manual__2024-05-28T22:08:30.636785+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/sales_data_pipeline.py', '--cfg-path', '/tmp/tmpy7cqel24']
[2024-05-28T22:14:25.743+0000] {standard_task_runner.py:91} INFO - Job 75: Subtask data_delivery
[2024-05-28T22:14:25.753+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T22:14:25.782+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:08:30.636785+00:00 [running]> on host 90e12a9d37bb
[2024-05-28T22:14:25.867+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud Mamdoh' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T22:08:30.636785+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T22:08:30.636785+00:00'
[2024-05-28T22:14:25.868+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T22:14:25.880+0000] {sales_data_pipeline.py:54} INFO - data_delivery started
[2024-05-28T22:14:25.881+0000] {sales_data_pipeline.py:61} ERROR - Error in data_delivery
Traceback (most recent call last):
  File "/opt/airflow/dags/sales_data_pipeline.py", line 55, in data_delivery
    load_customer_dim(**db_credentials)
TypeError: load_customer_dim() got an unexpected keyword argument 'host'
[2024-05-28T22:14:25.881+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T22:14:25.882+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T22:14:25.890+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=data_delivery, run_id=manual__2024-05-28T22:08:30.636785+00:00, execution_date=20240528T220830, start_date=20240528T221425, end_date=20240528T221425
[2024-05-28T22:14:25.914+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T22:14:25.931+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T22:14:25.933+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
