[2024-05-28T11:36:41.493+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T11:36:41.515+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.database_preparation manual__2024-05-28T11:36:40.011053+00:00 [queued]>
[2024-05-28T11:36:41.680+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.database_preparation manual__2024-05-28T11:36:40.011053+00:00 [queued]>
[2024-05-28T11:36:41.681+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-28T11:36:41.696+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): database_preparation> on 2024-05-28 11:36:40.011053+00:00
[2024-05-28T11:36:41.704+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T11:36:41.705+0000] {standard_task_runner.py:63} INFO - Started process 71 to run task
[2024-05-28T11:36:41.705+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'database_preparation', 'manual__2024-05-28T11:36:40.011053+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/sales_data_pipeline.py', '--cfg-path', '/tmp/tmpg4gv2z95']
[2024-05-28T11:36:41.707+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask database_preparation
[2024-05-28T11:36:41.746+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.database_preparation manual__2024-05-28T11:36:40.011053+00:00 [running]> on host 57dc34eafbbe
[2024-05-28T11:36:41.825+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud Mamdoh' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='database_preparation' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T11:36:40.011053+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T11:36:40.011053+00:00'
[2024-05-28T11:36:41.826+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T11:36:41.840+0000] {sales_data_pipeline.py:36} INFO - database_preparation started
[2024-05-28T11:36:41.841+0000] {sales_data_pipeline.py:41} ERROR - Error in database_preparation
Traceback (most recent call last):
  File "/opt/airflow/dags/sales_data_pipeline.py", line 37, in database_preparation
    drop_tables(**db_credentials)
TypeError: drop_tables() got an unexpected keyword argument 'host'
[2024-05-28T11:36:41.841+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T11:36:41.842+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T11:36:41.849+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=database_preparation, run_id=manual__2024-05-28T11:36:40.011053+00:00, execution_date=20240528T113640, start_date=20240528T113641, end_date=20240528T113641
[2024-05-28T11:36:41.878+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T11:36:41.900+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-28T11:36:41.902+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
