[2024-05-28T10:47:08.185+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T10:47:08.358+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.database_preparation manual__2024-05-28T10:47:06.728558+00:00 [queued]>
[2024-05-28T10:47:08.364+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.database_preparation manual__2024-05-28T10:47:06.728558+00:00 [queued]>
[2024-05-28T10:47:08.365+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-28T10:47:08.380+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): database_preparation> on 2024-05-28 10:47:06.728558+00:00
[2024-05-28T10:47:08.389+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1084) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T10:47:08.390+0000] {standard_task_runner.py:63} INFO - Started process 1086 to run task
[2024-05-28T10:47:08.390+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'database_preparation', 'manual__2024-05-28T10:47:06.728558+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/sales_data_pipeline.py', '--cfg-path', '/tmp/tmp2w_oiy6c']
[2024-05-28T10:47:08.392+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask database_preparation
[2024-05-28T10:47:08.433+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.database_preparation manual__2024-05-28T10:47:06.728558+00:00 [running]> on host 78f59380d06f
[2024-05-28T10:47:08.524+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud Mamdoh' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='database_preparation' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T10:47:06.728558+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T10:47:06.728558+00:00'
[2024-05-28T10:47:08.524+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T10:47:08.538+0000] {sales_data_pipeline.py:36} INFO - database_preparation started
[2024-05-28T10:47:08.538+0000] {sales_data_pipeline.py:41} ERROR - Error in database_preparation
Traceback (most recent call last):
  File "/opt/airflow/dags/sales_data_pipeline.py", line 37, in database_preparation
    drop_tables(**db_credentials)
TypeError: drop_tables() got an unexpected keyword argument 'host'
[2024-05-28T10:47:08.539+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T10:47:08.540+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T10:47:08.549+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=database_preparation, run_id=manual__2024-05-28T10:47:06.728558+00:00, execution_date=20240528T104706, start_date=20240528T104708, end_date=20240528T104708
[2024-05-28T10:47:08.603+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T10:47:08.631+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-28T10:47:08.633+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
