[2024-05-28T10:45:09.331+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T10:45:09.603+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.data_extraction manual__2024-05-28T10:45:04.936665+00:00 [queued]>
[2024-05-28T10:45:09.620+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.data_extraction manual__2024-05-28T10:45:04.936665+00:00 [queued]>
[2024-05-28T10:45:09.621+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-28T10:45:09.728+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_extraction> on 2024-05-28 10:45:04.936665+00:00
[2024-05-28T10:45:09.738+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1057) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T10:45:09.739+0000] {standard_task_runner.py:63} INFO - Started process 1059 to run task
[2024-05-28T10:45:09.740+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'data_extraction', 'manual__2024-05-28T10:45:04.936665+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/sales_data_pipeline.py', '--cfg-path', '/tmp/tmpqg33u9l0']
[2024-05-28T10:45:09.743+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask data_extraction
[2024-05-28T10:45:09.853+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.data_extraction manual__2024-05-28T10:45:04.936665+00:00 [running]> on host 78f59380d06f
[2024-05-28T10:45:10.053+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud Mamdoh' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='data_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T10:45:04.936665+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T10:45:04.936665+00:00'
[2024-05-28T10:45:10.054+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T10:45:10.070+0000] {sales_data_pipeline.py:45} INFO - data_extraction started
[2024-05-28T10:45:10.076+0000] {sales_data_pipeline.py:49} ERROR - Error in data_extraction
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/_optional.py", line 132, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/sales_data_pipeline.py", line 46, in data_extraction
    process_Ecommrese_data()
  File "/opt/airflow/dags/scripts/transform_data.py", line 7, in process_Ecommrese_data
    df = pd.read_excel('./datalake/bronze/E-commerce.xlsx')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 504, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1580, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_openpyxl.py", line 552, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2024-05-28T10:45:10.080+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T10:45:10.080+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T10:45:10.090+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=data_extraction, run_id=manual__2024-05-28T10:45:04.936665+00:00, execution_date=20240528T104504, start_date=20240528T104509, end_date=20240528T104510
[2024-05-28T10:45:10.154+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T10:45:10.179+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-28T10:45:10.223+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
