[2024-05-28T22:10:21.355+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T22:10:21.376+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.database_preparation manual__2024-05-28T22:08:30.636785+00:00 [queued]>
[2024-05-28T22:10:21.382+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.database_preparation manual__2024-05-28T22:08:30.636785+00:00 [queued]>
[2024-05-28T22:10:21.382+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-28T22:10:21.396+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): database_preparation> on 2024-05-28 22:08:30.636785+00:00
[2024-05-28T22:10:21.405+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=255) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T22:10:21.406+0000] {standard_task_runner.py:63} INFO - Started process 257 to run task
[2024-05-28T22:10:21.407+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'database_preparation', 'manual__2024-05-28T22:08:30.636785+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/sales_data_pipeline.py', '--cfg-path', '/tmp/tmpr_n5ycee']
[2024-05-28T22:10:21.408+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask database_preparation
[2024-05-28T22:10:21.419+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T22:10:21.446+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.database_preparation manual__2024-05-28T22:08:30.636785+00:00 [running]> on host 90e12a9d37bb
[2024-05-28T22:10:21.524+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud Mamdoh' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='database_preparation' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T22:08:30.636785+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T22:08:30.636785+00:00'
[2024-05-28T22:10:21.525+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T22:10:21.539+0000] {sales_data_pipeline.py:36} INFO - database_preparation started
[2024-05-28T22:10:21.539+0000] {sales_data_pipeline.py:41} ERROR - Error in database_preparation
Traceback (most recent call last):
  File "/opt/airflow/dags/sales_data_pipeline.py", line 37, in database_preparation
    drop_tables(**db_credentials)
TypeError: drop_tables() got an unexpected keyword argument 'database'
[2024-05-28T22:10:21.540+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T22:10:21.541+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T22:10:21.552+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=database_preparation, run_id=manual__2024-05-28T22:08:30.636785+00:00, execution_date=20240528T220830, start_date=20240528T221021, end_date=20240528T221021
[2024-05-28T22:10:21.579+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T22:10:21.603+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-28T22:10:21.604+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
