[2024-05-28T20:14:55.133+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T20:14:55.165+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.data_extraction manual__2024-05-28T20:14:51.546418+00:00 [queued]>
[2024-05-28T20:14:55.174+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.data_extraction manual__2024-05-28T20:14:51.546418+00:00 [queued]>
[2024-05-28T20:14:55.175+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-28T20:14:55.190+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_extraction> on 2024-05-28 20:14:51.546418+00:00
[2024-05-28T20:14:55.200+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=126) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T20:14:55.202+0000] {standard_task_runner.py:63} INFO - Started process 128 to run task
[2024-05-28T20:14:55.202+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'data_extraction', 'manual__2024-05-28T20:14:51.546418+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/sales_data_pipeline.py', '--cfg-path', '/tmp/tmphr02ipsf']
[2024-05-28T20:14:55.204+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask data_extraction
[2024-05-28T20:14:55.215+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T20:14:55.245+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.data_extraction manual__2024-05-28T20:14:51.546418+00:00 [running]> on host 90e12a9d37bb
[2024-05-28T20:14:55.369+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud Mamdoh' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='data_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T20:14:51.546418+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T20:14:51.546418+00:00'
[2024-05-28T20:14:55.370+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T20:14:55.386+0000] {sales_data_pipeline.py:45} INFO - data_extraction started
[2024-05-28T20:15:06.146+0000] {warnings.py:110} WARNING - /opt/***/dags/scripts/transform_data.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  store = df[['STORE_ID', 'Market', 'Region', 'Country']].drop_duplicates(subset=['STORE_ID'],inplace=True)

[2024-05-28T20:15:06.146+0000] {sales_data_pipeline.py:49} ERROR - Error in data_extraction
Traceback (most recent call last):
  File "/opt/airflow/dags/sales_data_pipeline.py", line 46, in data_extraction
    process_Ecommrese_data()
  File "/opt/airflow/dags/scripts/transform_data.py", line 15, in process_Ecommrese_data
    store =store.rename(columns={'STORE_ID':'store_id','Market':'market','Region':'region','Country':'country'})
           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'rename'
[2024-05-28T20:15:06.149+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T20:15:06.149+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T20:15:06.157+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=data_extraction, run_id=manual__2024-05-28T20:14:51.546418+00:00, execution_date=20240528T201451, start_date=20240528T201455, end_date=20240528T201506
[2024-05-28T20:15:06.222+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T20:15:06.244+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-28T20:15:06.245+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
